### ISSUE TITLE
Using Lock without Dialog API?

### ISSUE THREAD

**Issue by maxpaj** [OfficeDev/Office-Add-in-Auth0#3]
Hi Rick,

I used this example to setup authentication with Auth0 in my Office addin for Outlook. However, we've had some issues with Mac and the Dialog API. I'm now trying to use Lock in-line in the Taskpane, but I'm having some issues with that. I've posted a thread on Auth0's forum, I would appreciate it so much if you can give some input on it.

https://auth0.com/forum/t/authentication-error-we-couldnt-find-your-session/5700/4

**Comment by Rick-Kirkham** [comment]
Sorry. I'm not really an Auth0 expert. I think the suggestions that the Auth0 employee is making on that thread are good ones. If understand your last post to the thread which was after you created this issue (I think), you are past the initial problem.
