### ISSUE TITLE
Error with the dialog API

### ISSUE THREAD

**Issue by m1chaeldg** [OfficeDev/Office-Add-in-Auth0#4]
Hi, 
I used this as a sample app to do a little authentication on our custom OpenID server(Identity Server 4).
After the user signin and redirected to the popupredirect.html and there is a javascript that will call the post message to the parent windows and the reponse or error is always saying that the 
"Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://outlook.office.com') does not match the recipient window's origin ('https://localhost:3000').
invoke @ outlook-web-16.01.js:9"

Is there special requirement on how to test this or make the dialog API work?

Thanks

**Comment by Rick-Kirkham** [comment]
Are you getting this error from the sample as it is or did you modify it in some way?

**Comment by m1chaeldg** [comment]
Thanks Rick!

I managed to fix the error. So what I did I change the popup and use the custom open id. Modify also the APP domain in the manifest file.

**Comment by sguryev** [comment]
Hey guys, I have faced the same issue now. Do you know the generic solution? Have I missed something in the manifest?
![image](https://user-images.githubusercontent.com/6978458/47160024-b7f76900-d2f7-11e8-86a6-8031ef9fc16b.png)

I have tried to add the `https://outlook.office.com` to the AppDomains manifest list - no luck

**Comment by Rick-Kirkham** [comment]
@sguryev The Issues for this repo are intended to report problems with the sample "as is". It looks like you have an Angular-based add-in. Please raise this issue on StackOverflow where more people will see it and where the whole community will benefit from the answers that you get. Be sure to tag it `office-js` and `outlook-addin`.
