### ISSUE TITLE
How to enable silent auth?

### ISSUE THREAD

**Issue by maxpaj** [OfficeDev/Office-Add-in-Auth0#6]
Hi,

I've noticed that Silent auth doesn't work very well with my addin. I've asked in the community forum if it's possible to use refreshToken for keep the user logged in, but I got some vague answers.

I just now read up on this a little bit and seems like it could be related to 3rd party cookies not being allowed in the addin browser. Am I on the right track? 

How can I make silent auth work in my addin?

**Comment by Rick-Kirkham** [comment]
@maxpaj Thanks for working with Office Add-ins. This Issues forum is really for bugs with the sample. It would be great if you raise this question on StackOverflow. That way the whole community will see the answers you get. Please tag the question "office-js". Thanks, again.
